// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {main} from '../models';

export function ClearCommandHistory(arg1:string):Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function CreateFolder(arg1:domain.FileMutationInput):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteFile(arg1:domain.FileMutationInput):Promise<void>;

export function DeleteSavedCommand(arg1:string):Promise<void>;

export function GetMonitorIncidentReport(arg1:string):Promise<string>;

export function GetMonitorSnapshot(arg1:string):Promise<main.APIMonitorSnapshot>;

export function GetSettings():Promise<domain.AppSettings>;

export function ListCommandHistory(arg1:domain.CommandHistoryFilter):Promise<Array<main.APICommandHistoryEntry>>;

export function ListConnections():Promise<Array<main.APIConnection>>;

export function ListFiles(arg1:domain.FileListInput):Promise<Array<main.APIFileEntry>>;

export function ListMonitorHistory(arg1:domain.MonitorHistoryFilter):Promise<Array<main.APIMonitorHistoryEntry>>;

export function ListSavedCommands():Promise<Array<main.APISavedCommand>>;

export function OpenSession(arg1:domain.OpenSessionInput):Promise<main.APISession>;

export function ReadFile(arg1:domain.FileReadInput):Promise<main.APIFileContent>;

export function RecordCommandHistory(arg1:string,arg2:string):Promise<void>;

export function RenameFile(arg1:domain.FileRenameInput):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:domain.TerminalSize):Promise<void>;

export function RunCommand(arg1:domain.RunCommandInput):Promise<void>;

export function SaveConnection(arg1:domain.SaveConnectionInput):Promise<main.APIConnection>;

export function SaveFile(arg1:domain.FileSaveInput):Promise<void>;

export function SaveSavedCommand(arg1:domain.SaveSavedCommandInput):Promise<main.APISavedCommand>;

export function SaveSettings(arg1:domain.AppSettings):Promise<domain.AppSettings>;

export function SelectLocalDirectory(arg1:string):Promise<string>;

export function SelectLocalFile():Promise<string>;

export function SelectLocalFiles():Promise<Array<string>>;

export function SelectSaveFile(arg1:string):Promise<string>;

export function TestConnection(arg1:domain.TestConnectionInput):Promise<void>;

export function TransferFile(arg1:domain.FileTransferInput):Promise<domain.FileTransferResult>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
