// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function ListConnections():Promise<Array<domain.Connection>>;

export function OpenSession(arg1:domain.OpenSessionInput):Promise<domain.Session>;

export function ResizeTerminal(arg1:string,arg2:domain.TerminalSize):Promise<void>;

export function SaveConnection(arg1:domain.SaveConnectionInput):Promise<domain.Connection>;

export function TestConnection(arg1:domain.TestConnectionInput):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
