// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCommandHistory(arg1) {
  return window['go']['main']['App']['ClearCommandHistory'](arg1);
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteSavedCommand(arg1) {
  return window['go']['main']['App']['DeleteSavedCommand'](arg1);
}

export function GetMonitorIncidentReport(arg1) {
  return window['go']['main']['App']['GetMonitorIncidentReport'](arg1);
}

export function GetMonitorSnapshot(arg1) {
  return window['go']['main']['App']['GetMonitorSnapshot'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListCommandHistory(arg1) {
  return window['go']['main']['App']['ListCommandHistory'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ListMonitorHistory(arg1) {
  return window['go']['main']['App']['ListMonitorHistory'](arg1);
}

export function ListSavedCommands() {
  return window['go']['main']['App']['ListSavedCommands']();
}

export function OpenSession(arg1) {
  return window['go']['main']['App']['OpenSession'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RecordCommandHistory(arg1, arg2) {
  return window['go']['main']['App']['RecordCommandHistory'](arg1, arg2);
}

export function RenameFile(arg1) {
  return window['go']['main']['App']['RenameFile'](arg1);
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2);
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveSavedCommand(arg1) {
  return window['go']['main']['App']['SaveSavedCommand'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectLocalDirectory(arg1) {
  return window['go']['main']['App']['SelectLocalDirectory'](arg1);
}

export function SelectLocalFile() {
  return window['go']['main']['App']['SelectLocalFile']();
}

export function SelectLocalFiles() {
  return window['go']['main']['App']['SelectLocalFiles']();
}

export function SelectSaveFile(arg1) {
  return window['go']['main']['App']['SelectSaveFile'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TransferFile(arg1) {
  return window['go']['main']['App']['TransferFile'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
